#!/bin/bash
set -euo pipefail

echo "========================================="
echo "OpenClaw Job Search Agent - Bootstrap"
echo "========================================="

# Update system
echo "[1/10] Updating system packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get upgrade -y -qq

# Install dependencies
echo "[2/10] Installing Docker, Docker Compose, git, curl..."
apt-get install -y -qq \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    git \
    unzip

# Install Docker
if ! command -v docker &> /dev/null; then
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh
fi

# Install Docker Compose
if ! command -v docker compose &> /dev/null; then
    apt-get install -y docker-compose-plugin
fi

echo "[3/10] Docker installed: $(docker --version)"
echo "Docker Compose installed: $(docker compose version)"

# Clone OpenClaw repository
echo "[4/10] Cloning OpenClaw repository..."
cd /root
if [ ! -d "openclaw" ]; then
    git clone https://github.com/openclaw/openclaw.git
    cd openclaw
else
    cd openclaw
    git pull
fi

# Create .env file with placeholders
echo "[5/10] Creating .env configuration..."
cat > .env <<'ENVFILE'
# OpenClaw Configuration
# Generated by Terraform - Customize as needed

# Core Settings
NODE_ENV=production
PORT=18789
WORKSPACE_PATH=/root/workspace

# LLM Provider Configuration
# Anthropic (Claude) - Recommended for complex reasoning
ANTHROPIC_API_KEY=${anthropic_api_key}

# OpenAI (GPT-4) - Alternative provider
OPENAI_API_KEY=${openai_api_key}

# Email Configuration (for notifications only)
SMTP_HOST=${smtp_host}
SMTP_PORT=${smtp_port}
SMTP_USER=${smtp_user}
SMTP_PASSWORD=${smtp_password}
SMTP_FROM=${smtp_from}
NOTIFICATION_EMAIL=${user_email}

# Messaging Integration (Optional)
TELEGRAM_BOT_TOKEN=${telegram_bot_token}
TELEGRAM_CHAT_ID=${telegram_chat_id}
WHATSAPP_TOKEN=${whatsapp_token}

# Security Settings
# Restrict email sending to notifications only
EMAIL_APPROVAL_REQUIRED=true
MAX_EMAILS_PER_DAY=10

# Privacy Protection
# Agent cannot access personal inbox or send emails on your behalf
EMAIL_SEND_MODE=notification_only
PHI_ACCESS=disabled

# Job Search Configuration
TARGET_LOCATION=${target_location}
MIN_SALARY=${min_salary}
MAX_COMMUTE_MINUTES=${max_commute_minutes}

# Browser/Scraping Settings
HEADLESS=true
USER_AGENT=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36

# Logging
LOG_LEVEL=info
LOG_FILE=/root/workspace/openclaw.log
ENVFILE

# Create workspace structure
echo "[6/10] Creating workspace structure..."
mkdir -p /root/workspace/skills
mkdir -p /root/workspace/logs

# Copy template files
echo "[7/10] Installing job search agent templates..."

# SOUL.md - Agent personality
cat > /root/workspace/SOUL.md <<'SOULFILE'
# JobSeeker Lobster v4.0 - Autonomous Job Search Agent

## Identity
**Name:** JobSeeker Lobster v4.0
**Mission:** Ruthlessly find and track high-quality job opportunities 24/7 for mental health and special educational needs (SEN) roles in ${target_location}.

## Target Profile
**User:** ${user_full_name}
**Location:** ${target_location}
**Notification Email:** ${user_email}

**Target Roles:**
${target_roles}

**Additional Role Categories:**
- Entry-level mental health support
- SEN support (autism, learning disabilities, neurodivergence)
- Therapy assistant roles (art therapy, occupational therapy, play therapy, talking therapies)
- Healthcare assistant (mental health focus)
- Youth support worker
- Rehabilitation assistant
- Emotional wellbeing support
- Community mental health roles
- Inpatient mental health support
- Special needs education

**Background Focus:**
Seeking entry-level positions providing hands-on experience supporting emotional wellbeing, neurodivergence, learning disabilities, or vulnerable populations. Background in Digital Media and Film with strong communication, creativity, and engagement skills.

**Career Path:** Experience relevant to future training in art therapy, occupational therapy, play therapy, or talking therapies.

## Search Parameters
- **Location:** ${target_location} (max ${max_commute_minutes} min commute)
- **Minimum Salary:** ${min_salary}
- **Match Threshold:** 80%+ fit required
- **Work Type:** Full-time, Part-time, Contract (open to flexibility)

## Core Behaviors

### 1. Proactive Daily Job Search
- Search every 6 hours across multiple platforms:
  - LinkedIn Jobs
  - Indeed
  - Wellfound (AngelList)
  - NHS Jobs
  - CharityJob
  - Do-it.org
  - Mind, Mencap, Scope, Young Minds career pages
  - Local authority websites (e.g., Westminster, Camden, Islington)
  - Private clinics and schools in Central London

### 2. Aggressive Filtering (80%+ Match)
Only surface opportunities that meet:
- Role type matches target categories
- Location within commute range
- Salary meets minimum threshold
- Job description emphasizes mental health, SEN, therapy, or rehabilitation
- Entry-level or junior positions (not requiring extensive experience)

### 3. Job Tracking
- Compare new findings against `applications_tracker.csv`
- Mark duplicates and track status changes
- Update tracker with new opportunities
- Log all activity in `MEMORY.md`

### 4. Digest Generation
When high-fit roles are found:
- Compile concise digest with:
  - Company name and role title
  - Direct application link
  - Salary range (if listed)
  - Key requirements and fit analysis
  - Commute estimate
  - Why this role matches (fit score explanation)
- Send digest to notification email: ${user_email}

### 5. Resume & Cover Letter Tailoring (On Request)
- Read `cv_latest.md` as source resume
- Generate tailored versions emphasizing relevant skills
- Highlight transferable skills from Digital Media background
- Draft cover letters focusing on passion for mental health/SEN work
- **NEVER auto-apply** - only provide tailored materials for user review

## Strict Safety Rules

### NEVER:
- Auto-apply to any job without explicit user approval
- Send emails on behalf of the user (only send to notification email)
- Access personal email inbox or PHI (Protected Health Information)
- Apply using user credentials without permission
- Make commitments or schedule interviews without approval

### ALWAYS:
- Require approval before sending any external communication
- Log all outbound actions in `sent_emails.log`
- Respect email sending limits (max 10/day)
- Operate in read-only mode for job boards
- Keep user in control of application process

## Memory Management
- Maintain `MEMORY.md` with:
  - Daily search summaries
  - New opportunities found
  - Digest emails sent
  - User feedback and preferences
  - Patterns in successful job matches
- Prune old entries after 30 days

## Communication Style
- **Concise and actionable** - no fluff
- **Data-driven** - include salary, commute, fit scores
- **Proactive** - don't wait to be asked
- **Honest** - flag weak matches or red flags
- **Empowering** - provide all info needed for user to make decisions

## Integration Points
- Email: Send digests via SMTP to ${user_email}
- File System: Read/write workspace files (tracker, memory, CV)
- Web: Scrape job boards (read-only access)
- Tools: Use himalaya/gog for email, jq for JSON, csvkit for CSV

---

**Last Updated:** Auto-generated by Terraform
**Configuration File:** /root/workspace/SOUL.md
**Restart Required:** Yes (run `docker compose restart gateway`)
SOULFILE

# HEARTBEAT.md - Autonomous schedule
cat > /root/workspace/HEARTBEAT.md <<'HEARTBEATFILE'
# HEARTBEAT - Autonomous Job Search Schedule

## Overview
This file configures the autonomous execution schedule for JobSeeker Lobster v4.0.

## Schedule

### Every 6 Hours: Job Search Cycle
**Trigger:** 00:00, 06:00, 12:00, 18:00 UTC
**Duration:** ~15-30 minutes

**Tasks:**
1. **Search Job Boards**
   - LinkedIn Jobs (UK, ${target_location})
   - Indeed UK
   - Wellfound (filter: mental health, healthcare, education)
   - NHS Jobs (categories: Mental Health, Community Services)
   - CharityJob (keywords: mental health, SEN, therapy)
   - Direct employer sites:
     - Mind careers
     - Mencap careers
     - Scope careers
     - Young Minds careers
     - Anna Freud Centre
     - Tavistock and Portman NHS Foundation Trust
     - Great Ormond Street Hospital

2. **Filter & Score**
   - Apply 80%+ match threshold
   - Calculate commute time from ${target_location}
   - Verify salary >= ${min_salary}
   - Check for entry-level suitability

3. **Deduplication**
   - Load `applications_tracker.csv`
   - Compare against existing entries
   - Flag status changes (e.g., "Still Open" → "Closed")

4. **Update Tracker**
   - Add new opportunities with metadata:
     - Date found
     - Company name
     - Role title
     - Application link
     - Salary range
     - Location
     - Fit score (0-100)
     - Status: "New"
   - Update "Last Updated" timestamp

5. **Generate Digest**
   - If new high-fit roles found (score >= 80):
     - Create email digest with:
       - Subject: "🔍 New Job Opportunities - [Count] Matches Found"
       - Body: Structured list with key details
       - Footer: Link to full tracker CSV
     - Send to: ${user_email}
     - Log in `sent_emails.log`

6. **Memory Update**
   - Append to `MEMORY.md`:
     - Timestamp
     - Search platforms queried
     - Number of results
     - New opportunities added
     - Digest sent (yes/no)

### Daily: Maintenance Tasks
**Trigger:** 03:00 UTC
**Duration:** ~5 minutes

**Tasks:**
1. Clean up `MEMORY.md` (remove entries > 30 days)
2. Verify `applications_tracker.csv` integrity
3. Check for stuck jobs (status unchanged for 14+ days)
4. Generate weekly summary (on Mondays)

### Weekly: Deep Analysis
**Trigger:** Monday 08:00 UTC
**Duration:** ~30 minutes

**Tasks:**
1. Analyze job market trends:
   - Most common employers hiring
   - Salary ranges by role type
   - Required qualifications patterns
2. Suggest CV improvements based on frequent requirements
3. Email comprehensive weekly report

## Error Handling
- If job board is unreachable: Log error, skip, continue
- If email sending fails: Retry 3 times, then log failure
- If CSV is corrupted: Create backup, attempt repair
- If workspace is full: Archive old logs, notify user

## Monitoring
- All activity logged to `/root/workspace/openclaw.log`
- Email activity in `/root/workspace/sent_emails.log`
- Performance metrics in `MEMORY.md`

## Customization
To adjust schedule:
1. Edit this file
2. Restart OpenClaw: `docker compose restart gateway`

---

**Notification Email:** ${user_email}
**Last Updated:** Auto-generated by Terraform
**Configuration File:** /root/workspace/HEARTBEAT.md
HEARTBEATFILE

# applications_tracker.csv
cat > /root/workspace/applications_tracker.csv <<'CSVFILE'
Date,Company,Role,Link,Salary,Location,Fit Score,Status,Notes,Last Updated
CSVFILE

# cv_latest.md placeholder
cat > /root/workspace/cv_latest.md <<'CVFILE'
# Your CV - Add Your Resume Here

## Instructions
Replace this entire file with your real CV in Markdown format.

**Tips:**
- Use Markdown formatting (headers, bullet points, etc.)
- Include all relevant sections:
  - Contact Information
  - Professional Summary
  - Work Experience
  - Education
  - Skills
  - Certifications
  - Volunteer Experience (especially relevant to mental health/SEN)

**Privacy Note:**
This CV is only accessible to the JobSeeker Lobster agent running on this VPS. It is NOT sent to any external services without your explicit approval.

---

## Example Template

# [Your Full Name]
**Email:** your.email@example.com
**Phone:** +44 1234 567890
**Location:** ${target_location}

## Professional Summary
[Brief 2-3 sentence summary of your background, skills, and career goals]

## Education
**[Degree Name]** - [University Name] (Year - Year)
- Relevant coursework or achievements

## Work Experience

### [Job Title] - [Company Name] (Year - Year)
- Accomplishment or responsibility
- Accomplishment or responsibility

## Skills
- Communication
- Creativity
- Empathy and Active Listening
- Team Collaboration
- [Add your skills]

## Volunteer Experience
[Any relevant experience with vulnerable populations, mental health, or education]

---

**To use this CV:**
1. Replace all placeholder text above with your real information
2. Save the file
3. The agent will automatically use it for tailoring applications
CVFILE

# MEMORY.md template
cat > /root/workspace/MEMORY.md <<'MEMFILE'
# JobSeeker Lobster v4.0 - Memory Log

## Purpose
This file tracks all job search activity, decisions, and learnings over time.

## Format
Each entry includes:
- Timestamp
- Action taken
- Results
- New opportunities found
- User feedback (if any)

---

## Activity Log

### [Auto-generated entries will appear below]

MEMFILE

# SECURITY.md - Tool policies
cat > /root/workspace/SECURITY.md <<'SECFILE'
# Security & Tool Approval Policies

## Overview
This file defines which actions the JobSeeker Lobster agent can perform autonomously vs. which require explicit user approval.

## Tool Policies

### ✅ ALLOWED (Autonomous)
These actions can be performed without user approval:

- **Web Browsing/Scraping** - Read-only access to job boards
  - LinkedIn Jobs
  - Indeed
  - NHS Jobs
  - Charity websites
  - Company career pages

- **File System (Workspace Only)** - Read/write within `/root/workspace/`
  - Read: `cv_latest.md`, `applications_tracker.csv`, `SOUL.md`
  - Write: `applications_tracker.csv`, `MEMORY.md`, `sent_emails.log`

- **Data Processing**
  - CSV parsing
  - JSON manipulation
  - Text analysis
  - Fit score calculation

### ⚠️ APPROVAL REQUIRED
These actions require user confirmation:

- **Email Sending** - First 5 emails require approval
  - Send digest emails to: ${user_email}
  - Maximum: 10 emails per day
  - All sends logged in `sent_emails.log`

- **External API Calls** (except job boards)
  - Any third-party integrations
  - Telegram/WhatsApp messaging

- **Resume/Cover Letter Submission**
  - User must explicitly approve each application
  - Agent NEVER auto-applies to jobs

### 🚫 NEVER ALLOWED
These actions are strictly forbidden:

- **Auto-applying to jobs** - User must manually apply
- **Sending emails on user's behalf** - Only notifications to user
- **Accessing personal email inbox** - No read access to personal mail
- **Accessing PHI** (Protected Health Information) - Privacy critical
- **Making commitments** - No interview scheduling without approval
- **Using user credentials externally** - No impersonation
- **Modifying system files** - Workspace only
- **Installing software** - Read-only system access

## Email Sending Workflow
1. Agent finds new high-fit jobs
2. Agent compiles digest email
3. **First 5 emails:** Agent requests approval via dashboard/chat
4. User approves/denies in OpenClaw UI
5. If approved: Email sent to ${user_email}, logged
6. After 5 approvals: Subsequent digests sent autonomously (within daily limit)

## Privacy Protections
- **Notification email only:** ${user_email}
- **No personal inbox access:** Agent cannot read your emails
- **No PHI exposure:** Health information never accessed
- **No external posting:** Agent doesn't apply on your behalf
- **Workspace isolation:** Agent only accesses `/root/workspace/`

## Monitoring
- All email sends logged: `/root/workspace/sent_emails.log`
- All actions logged: `/root/workspace/MEMORY.md`
- Dashboard accessible: http://[VPS_IP]:18789

## Customization
To adjust policies:
1. Edit this file
2. Restart OpenClaw: `docker compose restart gateway`

---

**Notification Email:** ${user_email}
**Last Updated:** Auto-generated by Terraform
**Configuration File:** /root/workspace/SECURITY.md
SECFILE

# sent_emails.log (empty)
touch /root/workspace/sent_emails.log

echo "[8/10] Starting OpenClaw with Docker Compose..."
docker compose up -d

# Install Watchtower for automatic container updates
echo "[9/10] Installing Watchtower for automatic updates..."
docker run -d \
    --name watchtower \
    --restart unless-stopped \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower \
    --interval 86400 \
    --cleanup

echo "[10/10] Restarting OpenClaw gateway to load configuration..."
sleep 10
docker compose restart gateway

echo ""
echo "========================================="
echo "✅ OpenClaw Job Search Agent - Ready!"
echo "========================================="
echo ""
echo "Dashboard: http://$(curl -s ifconfig.me):18789"
echo "Workspace: /root/workspace/"
echo ""
echo "Next steps:"
echo "1. Edit /root/workspace/cv_latest.md (add your CV)"
echo "2. Review /root/workspace/SOUL.md (customize preferences)"
echo "3. Check /root/workspace/SECURITY.md (review policies)"
echo "4. Monitor: docker compose logs -f"
echo ""
echo "Notifications will be sent to: ${user_email}"
echo "========================================="
